### ISSUE TITLE
please don't place the pid file in /tmp

### ISSUE THREAD

**Issue by mbiebl** [WireGuard/wireguard-rs#3]
According to https://github.com/WireGuard/wireguard-rs/blob/master/src/main.rs#L66 the pid file is placed in /tmp with a predictable name. Please use a /run or /var/run for placing the pid file

**Comment by mbiebl** [comment]
See https://lwn.net/Articles/250468/

By placing the file in /run which is only writable by root you avoid this type of vulnerability

**Comment by saschagrunert** [comment]
Hey 👋. 

Yes this makes sense so we will change that.

**Comment by zx2c4** [comment]
This is a really embarrassing rookie error, and I suggest you get it fixed as soon as possible.

**Comment by mbiebl** [comment]
Related to that, please consider adding support for sd_notify to signal readiness when run in foreground mode: https://www.freedesktop.org/software/systemd/man/sd_notify.html

This avoids the need for pid files when run under systemd
