### ISSUE TITLE
copyright headers are invalid

### ISSUE THREAD

**Issue by zx2c4** [WireGuard/wireguard-rs#5]
```
// Copyright 2017 Sopium
```

This probably should change to:

```
Copyright 2017 Guanhao Yin <yinguanhao@gmail.com>
```

In addition to the other references of "Sopium". Generally projects from pseudonyms are controversial.

**Comment by sopium** [comment]
Replying to this issue as sopium. I do not confirm nor deny that I am Guanhao Yin.

IANAL but I believe claiming copyright under a pseudonyms is NOT INVALID, at least in my country.

It might be a bit controversial to release security related software under a pseudonyms. But the source code is there, available for review. And it's not like my real name would mean much anyway.

Closing and WONTFIX.

**Comment by zx2c4** [comment]
A lawyer indicated to me, in relation to this thread, the contrary: that it is problematic to release your code under any license at all to the public if you don't own it in the first place.

**Comment by sopium** [comment]
Alright, I'm inclined to follow your advice, now that you have an lawyer on your side.

Can you (or your lawyer friend) elaborate a bit on why it would be problematic?

I would argue that I do own the copyright, only it is under a pseudonym.

**Comment by zx2c4** [comment]
As I understand it, the reason is that when you give a license to somebody, they need for the grant of the license to be from a real person, made with their legal authority. When you have an anonymous copyright line, it's not clear that this is actually being done on behalf of the person with the legal authority. In the book publishing world, there are special provisions for pseudonyms in the copyright, provided that the pseudonym registers his real name and address with the copyright office through some official process; but I don't believe that procedure applies here. Anyway, it is for all these reasons that the Linux Kernel, also, does not accept pseudonymous submissions, which they have documented in the submission guidelines.
